### ISSUE TITLE
咨询关于 Indexs 文件夹中索引文件的生成方式

### ISSUE THREAD

**Issue by PilockHulmes** [AI-Hobbyist/StarRail_Voice_Sorting_Scripts#2]
首先感谢大佬分享的这么多工具与资源，有这些资源训练 AI 语音就方便多了。

然后我想请问一下 Indexs 文件夹中的索引文件是如何生成的。目前的索引文件中没有角色战斗语音相关信息，我在尝试练角色 AI 声音时想把战斗语音也加进去，所以想参考一下索引文件生成方式自己加入战斗语音部分。

**Comment by PilockHulmes** [comment]
我找到生成用的脚本了，再次感谢分享

**Comment by CattoYT** [comment]
抱歉打扰了这篇文章，但是您在哪里找到索引脚本？

我不会说中文，所以我用谷歌翻译
